Configuration WebServerConfig
{

    Node ("localhost") {

        WindowsFeature WebServer {
            Ensure = "Present"
            Name   = "Web-Server"
	    IncludeAllSubFeature = $true
        }
    }
}